import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import MockAdapter from 'axios-mock-adapter'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { apiClient, setAccessToken } from '../../services/api-client'
import { AuthContext } from '../auth/auth-context'
import type { Role } from '../auth/auth-types'
import { TopicPage } from './TopicPage'

const base = '/topics/api/v1/topics/'
const guid = '68317f4b-7445-45bf-8cbb-0c3ba05c5a50'
const rows = [
  { topic_id: 'DT001', name: 'Quản lý đồ án', description: 'SOA', avisor_name: 'An Nguyễn', major_name: 'Phần mềm' },
  { topic_id: 'DT002', name: 'Hệ thống thư viện', description: null, avisor_name: null, major_name: null },
]
const lecturer = { lecturer_id: 'GV001', department_id: '1', user: { first_name: 'An', last_name: 'Nguyễn' } }
const logout = vi.fn()
let mock: MockAdapter
beforeEach(() => {
  logout.mockReset(); setAccessToken('test-token')
  vi.spyOn(crypto, 'randomUUID').mockReturnValue(guid)
  mock = new MockAdapter(apiClient, { onNoMatch: 'throwException' })
  mock.onGet(base).reply(200, rows)
  mock.onGet('/academic/api/majors/').reply(200, [
    { major_id: '2', name: 'Phần mềm', department_id: '1' },
    { major_id: 'CNTT', name: 'Mã chữ', department_id: '1' },
  ])
  mock.onGet('/academic/api/v1/lecturers/').reply(200, [lecturer, { lecturer_id: 'GV002', department_id: null, user: null }])
})
afterEach(() => { mock.restore(); setAccessToken(null); vi.restoreAllMocks() })
function renderPage(role: Role = 1) {
  return render(<AuthContext.Provider value={{ user: { user_id: 'test-user', first_name: null, last_name: null, role }, logout, login: vi.fn(), status: 'ready', restoreError: '', retryRestore: vi.fn() }}><TopicPage /></AuthContext.Provider>)
}
async function openForm() {
  const opener = screen.getByRole('button', { name: 'Tạo đề tài' })
  opener.focus(); fireEvent.click(opener)
  await waitFor(() => expect(within(screen.getByRole('dialog')).getByRole('button', { name: 'Tạo đề tài' })).toBeEnabled())
  return screen.getByRole('form', { name: 'Tạo đề tài' })
}
function fillForm() {
  fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: '  Đề tài mới  ' } })
  fireEvent.change(screen.getByLabelText('Mô tả đề tài'), { target: { value: 'Mô tả SOA' } })
  fireEvent.change(screen.getByLabelText('Giáo viên hướng dẫn'), { target: { value: 'GV001' } })
  fireEvent.change(screen.getByLabelText('Ngành', { exact: true }), { target: { value: '2' } })
}

describe('Topic list and creation', () => {
  it('shows four business columns, topic actions and nullable names', async () => {
    renderPage()
    const table = await screen.findByRole('table', { name: 'Danh sách đề tài' })
    expect(within(table).getAllByRole('columnheader').map(cell => cell.textContent)).toEqual(['Mã đề tài', 'Tên đề tài', 'Giáo viên hướng dẫn', 'Tên ngành', 'Thao tác'])
    expect(within(table).getByText('An Nguyễn')).toBeVisible()
    expect(within(table).getByText('Phần mềm')).toBeVisible()
    expect(within(table).getAllByText('—')).toHaveLength(2)
    expect(mock.history.get.map(request => request.url)).toEqual([base])
  })
  it('searches by code or name only when Search is submitted', async () => {
    renderPage(); await screen.findByRole('table')
    const input = screen.getByRole('searchbox')
    fireEvent.change(input, { target: { value: '  dt001  ' } })
    expect(screen.getByText('DT002')).toBeVisible()
    fireEvent.click(screen.getByRole('button', { name: 'Search' }))
    expect(screen.queryByText('DT002')).not.toBeInTheDocument()
    fireEvent.change(input, { target: { value: 'THƯ VIỆN' } })
    expect(screen.getByText('DT001')).toBeVisible()
    fireEvent.submit(screen.getByRole('search'))
    expect(screen.getByText('DT002')).toBeVisible()
    expect(screen.queryByText('DT001')).not.toBeInTheDocument()
    fireEvent.change(input, { target: { value: 'no match' } }); fireEvent.submit(screen.getByRole('search'))
    expect(screen.getByText('Không có đề tài phù hợp.')).toBeVisible()
    expect(mock.history.get).toHaveLength(1)
  })
  it.each([1, 2] as const)('creates a GUID topic with selected reference IDs and refreshes the list for role %s', async role => {
    renderPage(role); await screen.findByRole('table')
    const form = await openForm()
    expect(screen.getByLabelText('Tên đề tài')).toHaveFocus()
    expect(screen.getByRole('option', { name: 'An Nguyễn (GV001)' })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: 'GV002' })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: /Mã chữ/ })).toBeDisabled()
    expect(screen.queryByRole('textbox', { name: 'Mã đề tài' })).not.toBeInTheDocument()
    fillForm()
    mock.onPost(base).reply(201, { ...rows[0], topic_id: guid })
    mock.onGet(base).reply(200, [...rows, { ...rows[0], topic_id: guid, name: 'Đề tài mới' }])
    fireEvent.submit(form)
    expect(await screen.findByText('Đã tạo đề tài.')).toBeVisible()
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(await screen.findByText(guid)).toBeVisible()
    expect(JSON.parse(mock.history.post[0].data)).toEqual({ topic_id: guid, name: 'Đề tài mới', description: 'Mô tả SOA', advisor_id: 'GV001', major_id: '2' })
    expect(mock.history.post[0].headers?.Authorization).toBe('Bearer test-token')
    expect(crypto.randomUUID).toHaveBeenCalledTimes(1)
    expect(screen.getByRole('button', { name: 'Tạo đề tài' })).toHaveFocus()
  })
  it('validates missing name and references before any POST', async () => {
    renderPage(); const form = await openForm()
    fireEvent.submit(form)
    expect(await screen.findByText('Vui lòng nhập tên đề tài.')).toBeVisible()
    expect(screen.getByText('Vui lòng chọn giáo viên hướng dẫn.')).toBeVisible()
    expect(screen.getByText('Vui lòng chọn ngành có mã số hợp lệ.')).toBeVisible()
    expect(screen.getByLabelText('Tên đề tài')).toHaveFocus()
    expect(mock.history.post).toHaveLength(0)
  })
  it('prevents duplicate submit and closing while a write is pending', async () => {
    let complete!: (response: [number, unknown]) => void
    mock.onPost(base).reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    renderPage(); const form = await openForm(); fillForm()
    fireEvent.submit(form); fireEvent.submit(form)
    await waitFor(() => expect(mock.history.post).toHaveLength(1))
    expect(screen.getByRole('button', { name: 'Đang lưu…' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Hủy' })).toBeDisabled()
    fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' })
    expect(screen.getByRole('dialog')).toBeVisible()
    await act(async () => complete([201, rows[0]]))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  })
  it.each([400, 403])('retains the form and GUID after HTTP %s without automatic retry', async status => {
    mock.onPost(base).reply(status, { name: ['invalid'], detail: 'private details' })
    renderPage(); const form = await openForm(); fillForm(); fireEvent.submit(form)
    expect(await screen.findByRole('alert')).toBeVisible()
    expect(screen.getByLabelText('Tên đề tài')).toHaveValue('  Đề tài mới  ')
    expect(screen.queryByText('private details')).not.toBeInTheDocument()
    expect(mock.history.post).toHaveLength(1)
    mock.onPost(base).reply(201, rows[0]); fireEvent.submit(form)
    await waitFor(() => expect(mock.history.post).toHaveLength(2))
    expect(JSON.parse(mock.history.post[1].data).topic_id).toBe(guid)
    expect(crypto.randomUUID).toHaveBeenCalledTimes(1)
  })
  it.each(['network', 'timeout', 409, 503] as const)('checks an ambiguous %s result before allowing another create', async failure => {
    const handler = mock.onPost(base)
    if (failure === 'network') handler.networkError()
    else if (failure === 'timeout') handler.timeout()
    else handler.reply(failure)
    renderPage(); const form = await openForm(); fillForm(); fireEvent.submit(form)
    const check = await screen.findByRole('button', { name: 'Kiểm tra kết quả' })
    expect(screen.getByLabelText('Tên đề tài')).toBeDisabled()
    fireEvent.submit(form)
    expect(mock.history.post).toHaveLength(1)
    mock.onGet(`${base}${guid}/`).reply(200, { ...rows[0], topic_id: guid })
    fireEvent.click(check)
    expect(await screen.findByText('Đã tạo đề tài.')).toBeVisible()
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(mock.history.post).toHaveLength(1)
  })
  it('allows explicit retry with the same GUID only after a result check returns 404', async () => {
    mock.onPost(base).timeout()
    renderPage(); const form = await openForm(); fillForm(); fireEvent.submit(form)
    mock.onGet(`${base}${guid}/`).reply(404)
    fireEvent.click(await screen.findByRole('button', { name: 'Kiểm tra kết quả' }))
    expect(await screen.findByText(/Chưa tìm thấy đề tài với mã này/)).toBeVisible()
    expect(screen.getByLabelText('Tên đề tài')).toBeEnabled()
    mock.onPost(base).reply(201, rows[0]); fireEvent.submit(form)
    await waitFor(() => expect(mock.history.post).toHaveLength(2))
    expect(JSON.parse(mock.history.post[1].data).topic_id).toBe(guid)
  })
  it('keeps an uncertain draft blocked when result checking also fails', async () => {
    mock.onPost(base).networkError()
    renderPage(); const form = await openForm(); fillForm(); fireEvent.submit(form)
    mock.onGet(`${base}${guid}/`).reply(503)
    fireEvent.click(await screen.findByRole('button', { name: 'Kiểm tra kết quả' }))
    expect(await screen.findByText(/Dịch vụ tạm thời/)).toBeVisible()
    expect(screen.getByLabelText('Tên đề tài')).toBeDisabled()
    expect(mock.history.post).toHaveLength(1)
  })
  it('keeps a successful write successful if refreshing the list fails', async () => {
    renderPage(); await screen.findByRole('table')
    const form = await openForm(); fillForm()
    mock.onPost(base).reply(201, rows[0]); mock.onGet(base).reply(503)
    fireEvent.submit(form)
    expect(await screen.findByText('Đã tạo đề tài.')).toBeVisible()
    expect(await screen.findByRole('alert')).toHaveTextContent('Dịch vụ tạm thời')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(mock.history.post).toHaveLength(1)
  })
  it.each(['list', 'options', 'create'] as const)('logs out on 401 from %s', async source => {
    if (source === 'list') mock.onGet(base).reply(401)
    if (source === 'options') mock.onGet('/academic/api/v1/lecturers/').reply(401)
    if (source === 'create') mock.onPost(base).reply(401)
    renderPage()
    if (source === 'options') fireEvent.click(screen.getByRole('button', { name: 'Tạo đề tài' }))
    if (source === 'create') { const form = await openForm(); fillForm(); fireEvent.submit(form) }
    await waitFor(() => expect(logout).toHaveBeenCalledOnce())
  })
  it.each(['network', 503] as const)('offers list retry after %s', async failure => {
    if (failure === 'network') mock.onGet(base).networkError()
    else mock.onGet(base).reply(failure)
    renderPage(); expect(await screen.findByRole('alert')).toBeVisible()
    expect(screen.queryByRole('table')).not.toBeInTheDocument()
    mock.onGet(base).reply(200, rows)
    fireEvent.click(screen.getByRole('button', { name: 'Tải lại' }))
    expect(await screen.findByRole('table')).toBeVisible()
  })
  it('disables creation until reference options load and offers retry', async () => {
    mock.onGet('/academic/api/majors/').reply(503)
    renderPage(); fireEvent.click(screen.getByRole('button', { name: 'Tạo đề tài' }))
    expect(await screen.findByRole('button', { name: 'Tải lại lựa chọn' })).toBeVisible()
    expect(within(screen.getByRole('dialog')).getByRole('button', { name: 'Tạo đề tài' })).toBeDisabled()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Giữ bản nháp' } })
    mock.onGet('/academic/api/majors/').reply(200, [{ major_id: '2', name: 'Phần mềm' }])
    fireEvent.click(screen.getByRole('button', { name: 'Tải lại lựa chọn' }))
    await waitFor(() => expect(screen.getByLabelText('Ngành', { exact: true })).toBeEnabled())
    expect(screen.getByLabelText('Tên đề tài')).toHaveValue('Giữ bản nháp')
  })
  it('shows missing reference choices without sending a write', async () => {
    mock.onGet('/academic/api/majors/').reply(200, [])
    renderPage(); const form = await openForm(); fireEvent.submit(form)
    expect(screen.getByText(/Chưa có giảng viên hoặc ngành/)).toBeVisible()
    expect(mock.history.post).toHaveLength(0)
  })
  it('renders a read-only list for students without reference requests', async () => {
    renderPage(3); await screen.findByRole('table')
    expect(screen.queryByRole('button', { name: 'Tạo đề tài' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Sửa DT001' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Xóa DT001' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Xem chi tiết DT001' })).toBeVisible()
    expect(mock.history.get.map(request => request.url)).toEqual([base])
  })
  it('aborts pending reference requests when the popup closes', async () => {
    let complete!: (response: [number, unknown]) => void
    mock.onGet('/academic/api/majors/').reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    renderPage(); fireEvent.click(screen.getByRole('button', { name: 'Tạo đề tài' }))
    await waitFor(() => expect(mock.history.get.some(request => request.url === '/academic/api/majors/')).toBe(true))
    const request = mock.history.get.find(request => request.url === '/academic/api/majors/')!
    fireEvent.click(screen.getByRole('button', { name: 'Hủy' }))
    expect(request.signal?.aborted).toBe(true)
    await act(async () => complete([401, {}]))
    expect(logout).not.toHaveBeenCalled()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
  it('aborts a pending POST on unmount and ignores a late 401', async () => {
    let complete!: (response: [number, unknown]) => void
    mock.onPost(base).reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    const view = renderPage(); const form = await openForm(); fillForm(); fireEvent.submit(form)
    await waitFor(() => expect(mock.history.post).toHaveLength(1))
    view.unmount()
    expect(mock.history.post[0].signal?.aborted).toBe(true)
    await act(async () => complete([401, {}]))
    expect(logout).not.toHaveBeenCalled()
  })
  it('aborts pending list loading on unmount', async () => {
    let complete!: (response: [number, unknown]) => void
    mock.onGet(base).reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    const view = renderPage()
    await waitFor(() => expect(mock.history.get).toHaveLength(1))
    view.unmount(); expect(mock.history.get[0].signal?.aborted).toBe(true)
    await act(async () => complete([401, {}]))
    expect(logout).not.toHaveBeenCalled()
  })
  it('closes on Escape and restores focus to the opener', async () => {
    renderPage(); await openForm()
    fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Tạo đề tài' })).toHaveFocus()
  })

  it('shows safe feedback if GUID generation is unavailable', async () => {
    vi.mocked(crypto.randomUUID).mockImplementation(() => { throw new Error('insecure context') })
    renderPage(); await screen.findByRole('table')
    fireEvent.click(screen.getByRole('button', { name: 'Tạo đề tài' }))
    expect(screen.getByRole('alert')).toHaveTextContent('HTTPS hoặc localhost')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(mock.history.post).toHaveLength(0)
  })

  it('shows a permission error for forbidden topic reads without logging out', async () => {
    mock.onGet(base).reply(403, { detail: 'private data' })
    renderPage(2)
    expect(await screen.findByRole('alert')).toHaveTextContent('Bạn không có quyền')
    expect(screen.queryByRole('table')).not.toBeInTheDocument()
    expect(screen.queryByText('private data')).not.toBeInTheDocument()
    expect(logout).not.toHaveBeenCalled()
  })
})

const detail = { ...rows[0], major_id: '2', advisor_id: 'GV001', file_url: '/files/topic.pdf', status: 1,
  created_at: '2026-10-10T08:00:00Z', updated_at: null, updated_by: 'admin' }
async function openEdit(role: Role = 2, searchQuery = '') {
  mock.onGet(base + 'DT001/').reply(200, detail)
  renderPage(role); await screen.findByRole('table')
  if (searchQuery) {
    fireEvent.change(screen.getByRole('searchbox'), { target: { value: searchQuery } })
    fireEvent.submit(screen.getByRole('search'))
  }
  fireEvent.click(screen.getByRole('button', { name: 'Sửa DT001' }))
  const form = await screen.findByRole('form', { name: 'Sửa đề tài' })
  await waitFor(() => expect(screen.getByRole('button', { name: 'Lưu thay đổi' })).toBeEnabled())
  return form
}
async function openDelete(role: Role = 2) {
  renderPage(role); await screen.findByRole('table')
  const opener = screen.getByRole('button', { name: 'Xóa DT001' })
  opener.focus(); fireEvent.click(opener)
  return screen.getByRole('dialog', { name: 'Xóa đề tài' })
}

describe('Topic detail, edit and delete', () => {
  it.each([1, 2, 3] as const)('fetches authoritative detail for role %s without academic requests', async role => {
    mock.onGet(base + 'DT001/').reply(200, { ...detail, name: 'Tên mới từ API', description: 'Mô tả chi tiết\nDòng hai' })
    renderPage(role); await screen.findByRole('table')
    const opener = screen.getByRole('button', { name: 'Xem chi tiết DT001' })
    opener.focus(); fireEvent.click(opener)
    const dialog = screen.getByRole('dialog', { name: 'Chi tiết đề tài' })
    expect(await within(dialog).findByText('Tên mới từ API')).toBeVisible()
    expect(within(dialog).getByText(/Mô tả chi tiết/)).toBeVisible()
    expect(within(dialog).getByText('/files/topic.pdf')).toBeVisible()
    expect(within(dialog).getByText('2026-10-10T08:00:00Z')).toBeVisible()
    expect(mock.history.get.map(request => request.url)).toEqual([base, base + 'DT001/'])
    fireEvent.keyDown(dialog, { key: 'Escape' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(opener).toHaveFocus()
  })
  it.each([403, 404, 503, 'network'] as const)('shows safe detail %s errors and supports explicit retry', async failure => {
    const handler = mock.onGet(base + 'DT001/')
    if (failure === 'network') handler.networkError()
    else handler.reply(failure, { detail: 'private upstream data' })
    renderPage(2); await screen.findByRole('table')
    fireEvent.click(screen.getByRole('button', { name: 'Xem chi tiết DT001' }))
    expect(await screen.findByRole('alert')).toBeVisible()
    expect(screen.queryByText('private upstream data')).not.toBeInTheDocument()
    expect(logout).not.toHaveBeenCalled()
    mock.onGet(base + 'DT001/').reply(200, detail)
    fireEvent.click(screen.getByRole('button', { name: 'Tải lại chi tiết' }))
    expect(await within(screen.getByRole('dialog')).findByText('SOA')).toBeVisible()
  })
  it('aborts closed detail reads and ignores late authorization failures', async () => {
    let complete!: (response: [number, unknown]) => void
    mock.onGet(base + 'DT001/').reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    renderPage(2); await screen.findByRole('table')
    fireEvent.click(screen.getByRole('button', { name: 'Xem chi tiết DT001' }))
    await waitFor(() => expect(mock.history.get).toHaveLength(2))
    fireEvent.click(screen.getByRole('button', { name: 'Đóng' }))
    expect(mock.history.get[1].signal?.aborted).toBe(true)
    await act(async () => complete([401, {}]))
    expect(logout).not.toHaveBeenCalled()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
  it.each([1, 2] as const)('prefills IDs and patches only changed fields for role %s, preserving search', async role => {
    const form = await openEdit(role, 'DT001')
    expect(screen.getByLabelText('Tên đề tài')).toHaveValue(detail.name)
    expect(screen.getByLabelText('Tên đề tài')).toHaveFocus()
    expect(screen.getByLabelText('Giáo viên hướng dẫn')).toHaveValue('GV001')
    expect(screen.getByLabelText('Ngành', { exact: true })).toHaveValue('2')
    expect(screen.queryByRole('textbox', { name: 'Mã đề tài' })).not.toBeInTheDocument()
    expect(screen.getByText(/DT001 \(không thể thay đổi\)/)).toBeVisible()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: '  Đổi tên  ' } })
    mock.onPatch(base + 'DT001/').reply(200, { ...detail, name: 'Đổi tên' })
    mock.onGet(base).reply(200, [{ ...rows[0], name: 'Đổi tên' }, rows[1]])
    fireEvent.submit(form)
    expect(await screen.findByText('Đã cập nhật đề tài.')).toBeVisible()
    expect(await screen.findByText('Đổi tên')).toBeVisible()
    expect(JSON.parse(mock.history.patch[0].data)).toEqual({ name: 'Đổi tên' })
    expect(mock.history.patch[0].headers?.Authorization).toBe('Bearer test-token')
    expect(mock.history.post).toHaveLength(0)
    expect(crypto.randomUUID).not.toHaveBeenCalled()
    expect(screen.getByRole('searchbox')).toHaveValue('DT001')
    expect(screen.queryByText('DT002')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Tải lại' }))
    await waitFor(() => expect(screen.getByText('Đổi tên')).toBeVisible())
    expect(screen.queryByText('DT002')).not.toBeInTheDocument()
  })
  it('allows unchanged legacy references even when names/options are absent', async () => {
    mock.onGet(base + 'DT001/').reply(200, { ...detail, major_id: 'LEGACY', advisor_id: null, major_name: null, avisor_name: null })
    mock.onGet('/academic/api/majors/').reply(200, [])
    mock.onGet('/academic/api/v1/lecturers/').reply(200, [])
    renderPage(2); await screen.findByRole('table')
    fireEvent.click(screen.getByRole('button', { name: 'Sửa DT001' }))
    const form = await screen.findByRole('form', { name: 'Sửa đề tài' })
    await waitFor(() => expect(screen.getByRole('button', { name: 'Lưu thay đổi' })).toBeEnabled())
    expect(screen.getByLabelText('Ngành', { exact: true })).toHaveValue('LEGACY')
    fireEvent.change(screen.getByLabelText('Mô tả đề tài'), { target: { value: 'Mô tả sửa' } })
    mock.onPatch(base + 'DT001/').reply(200, detail)
    fireEvent.submit(form)
    expect(await screen.findByText('Đã cập nhật đề tài.')).toBeVisible()
    expect(JSON.parse(mock.history.patch[0].data)).toEqual({ description: 'Mô tả sửa' })
  })
  it('sends selected reference IDs without resending untouched description', async () => {
    mock.onGet('/academic/api/majors/').reply(200, [{ major_id: '2', name: 'A' }, { major_id: '3', name: 'A' }])
    const form = await openEdit()
    fireEvent.change(screen.getByLabelText('Ngành', { exact: true }), { target: { value: '3' } })
    fireEvent.change(screen.getByLabelText('Giáo viên hướng dẫn'), { target: { value: 'GV002' } })
    mock.onPatch(base + 'DT001/').reply(200, detail)
    fireEvent.submit(form)
    expect(await screen.findByText('Đã cập nhật đề tài.')).toBeVisible()
    expect(JSON.parse(mock.history.patch[0].data)).toEqual({ major_id: '3', advisor_id: 'GV002' })
  })
  it('validates changed edit fields and does not patch an unchanged draft', async () => {
    const form = await openEdit()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: '  ' } })
    fireEvent.change(screen.getByLabelText('Ngành', { exact: true }), { target: { value: '' } })
    fireEvent.change(screen.getByLabelText('Giáo viên hướng dẫn'), { target: { value: '' } })
    fireEvent.submit(form)
    expect(await screen.findByText('Vui lòng nhập tên đề tài.')).toBeVisible()
    expect(screen.getByText('Vui lòng chọn giáo viên hướng dẫn.')).toBeVisible()
    expect(screen.getByText('Vui lòng chọn ngành có mã số hợp lệ.')).toBeVisible()
    expect(screen.getByLabelText('Tên đề tài')).toHaveFocus()
    expect(mock.history.patch).toHaveLength(0)
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: detail.name } })
    fireEvent.change(screen.getByLabelText('Ngành', { exact: true }), { target: { value: '2' } })
    fireEvent.change(screen.getByLabelText('Giáo viên hướng dẫn'), { target: { value: 'GV001' } })
    fireEvent.submit(form)
    expect(await screen.findByText('Không có thay đổi.')).toBeVisible()
    expect(mock.history.patch).toHaveLength(0)
  })
  it.each([400, 403, 404, 409])('keeps the edit draft after HTTP %s without retrying', async status => {
    const form = await openEdit()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Tên đang sửa' } })
    mock.onPatch(base + 'DT001/').reply(status, { name: ['invalid'], detail: 'private upstream data' })
    fireEvent.submit(form)
    expect(await screen.findByRole('alert')).toBeVisible()
    expect(screen.getByLabelText('Tên đề tài')).toHaveValue('Tên đang sửa')
    expect(screen.queryByText('private upstream data')).not.toBeInTheDocument()
    expect(mock.history.patch).toHaveLength(1)
    expect(logout).not.toHaveBeenCalled()
  })
  it('blocks duplicate PATCH and close while saving', async () => {
    let complete!: (response: [number, unknown]) => void
    const form = await openEdit()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Tên mới' } })
    mock.onPatch(base + 'DT001/').reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    fireEvent.submit(form); fireEvent.submit(form)
    await waitFor(() => expect(mock.history.patch).toHaveLength(1))
    expect(screen.getByRole('button', { name: 'Hủy' })).toBeDisabled()
    fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' })
    expect(screen.getByRole('dialog')).toBeVisible()
    await act(async () => complete([200, detail]))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  })
  it.each(['network', 'timeout', 503] as const)('reconciles an ambiguous PATCH %s using changed field values', async failure => {
    const form = await openEdit()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Tên mới' } })
    const handler = mock.onPatch(base + 'DT001/')
    if (failure === 'network') handler.networkError()
    else if (failure === 'timeout') handler.timeout()
    else handler.reply(failure)
    fireEvent.submit(form)
    const check = await screen.findByRole('button', { name: 'Kiểm tra kết quả' })
    fireEvent.submit(form)
    expect(mock.history.patch).toHaveLength(1)
    mock.onGet(base + 'DT001/').reply(200, { ...detail, name: 'Tên mới' })
    fireEvent.click(check)
    expect(await screen.findByText('Đã xác nhận dữ liệu cập nhật.')).toBeVisible()
    expect(mock.history.patch).toHaveLength(1)
  })
  it('does not claim a timed-out edit succeeded just because the topic exists', async () => {
    const form = await openEdit()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Tên chưa lưu' } })
    mock.onPatch(base + 'DT001/').timeout()
    fireEvent.submit(form)
    fireEvent.click(await screen.findByRole('button', { name: 'Kiểm tra kết quả' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('chưa khớp bản sửa')
    expect(screen.getByLabelText('Tên đề tài')).toHaveValue('Tên chưa lưu')
    expect(mock.history.patch).toHaveLength(1)
    expect(screen.queryByText('Đã cập nhật đề tài.')).not.toBeInTheDocument()
  })
  it('fails safely when management detail lacks reference IDs', async () => {
    mock.onGet(base + 'DT001/').reply(200, { ...detail, major_id: undefined, advisor_id: undefined })
    renderPage(2); await screen.findByRole('table')
    fireEvent.click(screen.getByRole('button', { name: 'Sửa DT001' }))
    expect(await screen.findByRole('alert')).toBeVisible()
    expect(screen.queryByRole('form', { name: 'Sửa đề tài' })).not.toBeInTheDocument()
    expect(mock.history.patch).toHaveLength(0)
  })
  it('cancels delete without sending a write and restores focus', async () => {
    const dialog = await openDelete()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Hủy' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(mock.history.delete).toHaveLength(0)
    expect(screen.getByRole('button', { name: 'Xóa DT001' })).toHaveFocus()
  })
  it.each([1, 2] as const)('deletes only after confirmation for role %s and refreshes the list', async role => {
    const dialog = await openDelete(role)
    expect(mock.history.delete).toHaveLength(0)
    mock.onDelete(base + 'DT001/').reply(204)
    mock.onGet(base).reply(200, [rows[1]])
    fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    expect(await screen.findByText('Đã xóa đề tài.')).toBeVisible()
    await waitFor(() => expect(screen.queryByText('DT001')).not.toBeInTheDocument())
    expect(mock.history.delete).toHaveLength(1)
    expect(mock.history.delete[0].headers?.Authorization).toBe('Bearer test-token')
  })
  it('keeps referenced topics after a 409 delete conflict', async () => {
    const dialog = await openDelete()
    mock.onDelete(base + 'DT001/').reply(409)
    fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('dữ liệu liên kết')
    expect(mock.history.delete).toHaveLength(1)
    fireEvent.click(screen.getByRole('button', { name: 'Hủy' }))
    expect(within(screen.getByRole('table')).getByText('DT001')).toBeVisible()
  })
  it.each([401, 403])('handles delete HTTP %s without repeated writes', async status => {
    const dialog = await openDelete()
    mock.onDelete(base + 'DT001/').reply(status, { detail: 'private upstream data' })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    if (status === 401) await waitFor(() => expect(logout).toHaveBeenCalledOnce())
    else expect(await screen.findByRole('alert')).toHaveTextContent('Bạn không có quyền')
    expect(screen.queryByText('private upstream data')).not.toBeInTheDocument()
    expect(mock.history.delete).toHaveLength(1)
  })
  it('blocks duplicate delete and closing while pending', async () => {
    let complete!: (response: [number, unknown]) => void
    const dialog = await openDelete()
    mock.onDelete(base + 'DT001/').reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    const confirm = within(dialog).getByRole('button', { name: 'Xác nhận xóa' })
    fireEvent.click(confirm); fireEvent.click(confirm)
    await waitFor(() => expect(mock.history.delete).toHaveLength(1))
    expect(within(dialog).getByRole('button', { name: 'Hủy' })).toBeDisabled()
    fireEvent.keyDown(dialog, { key: 'Escape' })
    expect(dialog).toBeVisible()
    await act(async () => complete([204, undefined]))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  })
  it.each(['network', 'timeout', 503] as const)('checks an ambiguous delete %s before permitting another request', async failure => {
    const dialog = await openDelete()
    const handler = mock.onDelete(base + 'DT001/')
    if (failure === 'network') handler.networkError()
    else if (failure === 'timeout') handler.timeout()
    else handler.reply(failure)
    fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    const check = await screen.findByRole('button', { name: 'Kiểm tra kết quả' })
    expect(screen.queryByRole('button', { name: 'Xác nhận xóa' })).not.toBeInTheDocument()
    mock.onGet(base + 'DT001/').reply(404)
    fireEvent.click(check)
    expect(await screen.findByText('Đã xác nhận đề tài không còn tồn tại.')).toBeVisible()
    expect(mock.history.delete).toHaveLength(1)
  })
  it('handles an already-deleted topic without claiming a new delete succeeded', async () => {
    const dialog = await openDelete()
    mock.onDelete(base + 'DT001/').reply(404)
    mock.onGet(base).reply(200, [rows[1]])
    fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    expect(await screen.findByText('Đề tài không còn tồn tại.')).toBeVisible()
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.queryByText('Đã xóa đề tài.')).not.toBeInTheDocument()
    expect(mock.history.delete).toHaveLength(1)
  })
  it('keeps an uncertain delete blocked when result checking fails', async () => {
    const dialog = await openDelete()
    mock.onDelete(base + 'DT001/').timeout()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    mock.onGet(base + 'DT001/').reply(503)
    fireEvent.click(await screen.findByRole('button', { name: 'Kiểm tra kết quả' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Dịch vụ tạm thời')
    expect(screen.queryByRole('button', { name: 'Xác nhận xóa' })).not.toBeInTheDocument()
    expect(mock.history.delete).toHaveLength(1)
  })
  it('reconciles edited description using the serializer whitespace normalization', async () => {
    const form = await openEdit()
    fireEvent.change(screen.getByLabelText('Mô tả đề tài'), { target: { value: '  Mô tả mới  ' } })
    mock.onPatch(base + 'DT001/').timeout()
    fireEvent.submit(form)
    mock.onGet(base + 'DT001/').reply(200, { ...detail, description: 'Mô tả mới' })
    fireEvent.click(await screen.findByRole('button', { name: 'Kiểm tra kết quả' }))
    expect(await screen.findByText('Đã xác nhận dữ liệu cập nhật.')).toBeVisible()
    expect(JSON.parse(mock.history.patch[0].data)).toEqual({ description: 'Mô tả mới' })
  })
  it('requires renewed confirmation when a delete result check finds the topic still present', async () => {
    const dialog = await openDelete()
    mock.onDelete(base + 'DT001/').timeout()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    mock.onGet(base + 'DT001/').reply(200, rows[0])
    fireEvent.click(await screen.findByRole('button', { name: 'Kiểm tra kết quả' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('vẫn tồn tại')
    expect(screen.getByRole('button', { name: 'Xác nhận xóa' })).toBeEnabled()
    expect(mock.history.delete).toHaveLength(1)
  })
  it.each(['detail', 'edit', 'delete'] as const)('logs out on 401 from %s requests', async source => {
    if (source === 'edit') {
      const form = await openEdit()
      mock.onPatch(base + 'DT001/').reply(401)
      fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Tên sửa' } })
      fireEvent.submit(form)
    } else if (source === 'delete') {
      const dialog = await openDelete()
      mock.onDelete(base + 'DT001/').reply(401)
      fireEvent.click(within(dialog).getByRole('button', { name: 'Xác nhận xóa' }))
    } else {
      mock.onGet(base + 'DT001/').reply(401)
      renderPage(2); await screen.findByRole('table')
      fireEvent.click(screen.getByRole('button', { name: 'Xem chi tiết DT001' }))
    }
    await waitFor(() => expect(logout).toHaveBeenCalledOnce())
  })
  it.each(['edit', 'delete'] as const)('aborts pending %s on unmount without acting on a late 401', async action => {
    let complete!: (response: [number, unknown]) => void
    mock.onGet(base + 'DT001/').reply(200, detail)
    const view = renderPage(2); await screen.findByRole('table')
    fireEvent.click(screen.getByRole('button', { name: action === 'edit' ? 'Sửa DT001' : 'Xóa DT001' }))
    const handler = action === 'edit' ? mock.onPatch(base + 'DT001/') : mock.onDelete(base + 'DT001/')
    handler.reply(() => new Promise<[number, unknown]>(resolve => { complete = resolve }))
    if (action === 'edit') {
      const form = await screen.findByRole('form', { name: 'Sửa đề tài' })
      await waitFor(() => expect(screen.getByRole('button', { name: 'Lưu thay đổi' })).toBeEnabled())
      fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Tên sửa' } })
      fireEvent.submit(form)
    } else fireEvent.click(screen.getByRole('button', { name: 'Xác nhận xóa' }))
    const history = () => action === 'edit' ? mock.history.patch : mock.history.delete
    await waitFor(() => expect(history()).toHaveLength(1))
    view.unmount()
    expect(history()[0].signal?.aborted).toBe(true)
    await act(async () => complete([401, {}]))
    expect(logout).not.toHaveBeenCalled()
  })
})
